server:
  port:
spring:
  datasource:
    driver-class-name :
    url:
    username:
    password":
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true